### ISSUE TITLE
Always allow assignment to inferred:"undef"

### ISSUE THREAD

**Issue by mraak** [getify/TypVal#9]
Always allow assignment to inferred:"undef" and **do** overwrite the type

**Comment by mraak** [comment]
```
var a
a = 2
a = "i"
a = 4

Assignment type mismatch: expected type 'number', but found type 'undef'
Assignment type mismatch: expected type 'string', but found type 'number'

```

The above test shows that _undef_ type adopts the type from the first assignment.

**Comment by getify** [comment]
Example:

```js
var a;
var b = a + 1;   // error: mixed operand types

a = 2;   // no error, overwrites `a` to type `number`
b = a + 2;  // no error

var c = undefined;
c = 3;  // no error

var d = undef``;
d = 4;  // error, `d` is tagged-type of `undefined`
```

**Comment by getify** [comment]
see: https://github.com/getify/TypVal/pull/10

**Comment by mraak** [comment]
How about this.

```
var i
i = null
```

and 

```
var i = undef``
i = null
```

I see that TypVal sees `null` as `unknown`, as opposed to `NullLiteral` as AST sees it. Is this a bug?

**Comment by getify** [comment]
> I see that TypVal sees `null` as `unknown`, as opposed to `NullLiteral` as AST sees it. Is this a bug?

Yes, good catch... there should be a visitor for `NullLiteral` that sets the inferred type to `"nul"` (note the one "l").

**Comment by mraak** [comment]
OK, I'll see if I can fix it. And how should it react to assignment to inferred-undef and tagged-undef? See the previous comment.

**Comment by getify** [comment]
> how should it react to assignment to inferred-undef and tagged-undef

The way I wrote the code that you merged, the first snippet will work fine, but the second one will throw an error.

**Comment by getify** [comment]
The `NullLiteral` visitor should look something like this:

```js
NullLiteral: {
   exit(path) {
      nodeTypes.set(path.node,{ inferred: 'nul', });
   },
},
```

**Comment by mraak** [comment]
On my branch it now works as expected I think.

**Comment by getify** [comment]
Great. See: https://github.com/getify/TypVal/commit/f522dba9627ef69d5249dee276aaed2d9e6b3bec#commitcomment-32308741

**Comment by mraak** [comment]
Could we close this one?
